services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - OSCAL_FEED_URL=https://raw.githubusercontent.com/AustralianCyberSecurityCentre/ism-oscal/main/controls.json

  db:
    build: ./db
    environment:
      - POSTGRES_DB=ism
      - POSTGRES_USER=ism
      - POSTGRES_PASSWORD=ism
    volumes:
      - db-data:/var/lib/postgresql/data

  feed:
    build: ./feed
    environment:
      - DB_HOST=db
      - DB_NAME=ism
      - DB_USER=ism
      - DB_PASS=ism

volumes:
  db-data:
