services:
  web:
    build: ./www
    ports:
      - "8080:80"
    depends_on:
      - feed
      - db
    environment:
      - OSCAL_FEED_URL=https://raw.githubusercontent.com/AustralianCyberSecurityCentre/ism-oscal/main/controls.json

  feed:
    build: ./feed
    depends_on:
      - db
    dns:
      - 1.1.1.1
      - 8.8.8.8

  db:
    build: ./db
    environment:
      - POSTGRES_DB=ism
      - POSTGRES_USER=ism
      - POSTGRES_PASSWORD=ism
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
